### ISSUE TITLE
Add a command to "Search for a string/pattern within a file/standard input"

### ISSUE THREAD

**Issue by smv1999** [smv1999/pysh#2]
Add a cross-platform command implementation to search for a string/pattern within an file/standard input similar to 'grep' in Linux.

**Comment by kalashjain23** [comment]
Hey! I would like to take up on this issue as a student in SLOP 2.0. Please assign this issue to me!

**Comment by smv1999** [comment]
Sure, go ahead @kalashjain23

**Comment by kalashjain23** [comment]
Hey! I was thinking of solving this issue using the Boyer-Moore algorithm (used in GNU grep as well), so am I allowed to make a separate python file in `utils.py` for that algorithm (namely `boyer_moore_algorithm.py`) in order to keep `pysh.py` clean? Or do I have to write that algorithm in `pysh.py` itself?

**Comment by smv1999** [comment]
Yes @kalashjain23 . You can go ahead and create a separate file for that algorithm.

**Comment by kalashjain23** [comment]
Hey! Can you please review my PR and tell the required changes to be made!

**Comment by smv1999** [comment]
Sure @kalashjain23
